---
openrpc: 1.2.6
info:
  title: BLE Gateway DM Firmware
  version: 1.1.1
  x-default-baud: 115200
methods:
  - $ref: ./../modules/lib/laird_connect/zephyr_lib/components/attributes/os_mgmt_methods.yml
  - $ref: ./../modules/lib/laird_connect/zephyr_lib/components/attributes/os_mgmt_mcumgr_params_methods.yml
  - $ref: ./../modules/lib/laird_connect/attributes/attributes/attributes_methods.yml
  - $ref: ./../modules/lib/laird_connect/zephyr_lib/components/attributes/lcz_fs_mgmt_methods.yml
  - $ref: ./../modules/lib/laird_connect/zephyr_lib/components/attributes/shell_mgmt_methods.yml
components:
  contentDescriptors:
    device_params:
      name: device_parameters
      schema:
        type: array
      x-device-parameters:
        - $ref: ./app/attributes/app_params.yml
        - $ref: ../modules/lib/laird_connect/lwm2m_client/attributes/params.yml
        - $ref: ../modules/lib/laird_connect/lwm2m_firmware_update/attributes/params.yml
        - $ref: ../modules/lib/laird_connect/ble_gateway_device_manager/attributes/params.yml
        - $ref: ../modules/lib/laird_connect/shell_login/attributes/params.yml
        - $ref: ../modules/lib/laird_connect/pki_auth/attributes/params.yml
        - $ref: ../modules/lib/laird_connect/network_monitor/attributes/params.ipv4.yml
        - $ref: ../modules/lib/laird_connect/lcz_sensor_telemetry_app/attributes/lcz_sensor_app.yml
        - $ref: ../modules/lib/laird_connect/zephyr_lib/memfault/attributes/params.yml
      x-mg100:
        - $ref: ../modules/lib/laird_connect/modem_hl7800/attributes/params.yml
      x-p100:
        - $ref: ../modules/lib/laird_connect/modem_hl7800/attributes/params.yml
      x-bl5340:
        - $ref: ../modules/lib/laird_connect/network_monitor/attributes/params.gw_ipv4.yml
      x-lwm2m:
        - $ref: ../modules/lib/laird_connect/ble_gateway_device_manager/attributes/params_lwm2m_telem.yml
      x-mqtt:
        - $ref: ../modules/lib/laird_connect/lcz_mqtt/attributes/lcz_mqtt.yml
        - $ref: ../modules/lib/laird_connect/lcz_sensor_telemetry_app/attributes/lcz_sensor_app_mqtt.yml
